# Project information
site_name: BBOT Docs
site_url: https://blacklanternsecurity.github.io/bbot/
site_author: TheTechromancer
site_description: >-
  OSINT automation for hackers
# Repository
repo_name: blacklanternsecurity/bbot
repo_url: https://github.com/blacklanternsecurity/bbot

# Page tree
nav:
  - Basics:
    - Getting Started: index.md
    - How it Works: how_it_works.md
    - Comparison to Other Tools: comparison.md
  - Scanning:
    - Scanning Overview: scanning/index.md
    - Events: scanning/events.md
    - Output: scanning/output.md
    - Tips and Tricks: scanning/tips_and_tricks.md
    - Advanced Usage: scanning/advanced.md
    - Configuration: scanning/configuration.md
    - List of Modules: scanning/list_of_modules.md
  - Contribution:
    - How to Write a Module: contribution.md
  - Misc:
    - Release History: release_history.md
    - Troubleshooting: troubleshooting.md

theme:
  name: material
  logo: bbot.png
  features:
    - content.code.copy
    - navigation.sections
    - navigation.expand
    - toc.integrate
  palette:
    - scheme: slate
      primary: black
      accent: deep orange

plugins:
  - search
  - extra-sass

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: True
      noclasses: True
      pygments_style: github-dark
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
